export enum RouterPaths {
  AUTH = '/auth',
  CREATE_NEW_PASSWORD = '/auth/create-new-password',
  EXPIRED_LINK = '/auth/expired-link',
  FORGOT_PASSWORD = '/auth/forgot-password',
  HOME = '/',
  MY_PROFILE = '/my-profile',
  PERSONAL_INFO = '/personal-info',
  PRIVACY_POLICY = '/auth/privacy-policy',
  RECOVERY = '/auth/recovery',
  REGISTRATION_CONFIRMATION = '/auth/registration-confirmation',
  SIGN_IN = '/auth/sign-in',
  SIGN_UP = '/auth/sign-up',
  TERMS_OF_SERVICE = '/auth/terms-of-service',
  VERIFICATION_LINK = '/auth/verification-link',
}
